EXE: Main.cpp Energy.cpp EXWL.cpp Init.cpp Mov.cpp Mov_Other.cpp Mov_Pivot.cpp Mov_Pull.cpp Mov_Rebridge.cpp Reorg.cpp Globals.h
	mpiCC -o EXE Main.cpp Energy.cpp EXWL.cpp Init.cpp Mov.cpp Mov_Other.cpp Mov_Pivot.cpp Mov_Pull.cpp Mov_Rebridge.cpp Reorg.cpp Globals.h -lm
